using JobCv.Api.Dtos;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace JobCv.Api.Pdf
{
    public class CareerTestPdfDocument : IDocument
    {
        private readonly CareerTestPdfRequestDto _result;

        public CareerTestPdfDocument(CareerTestPdfRequestDto result)
        {
            _result = result;
        }

        public DocumentMetadata GetMetadata()
        {
            return DocumentMetadata.Default;
        }

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(36);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(10).FontColor("#334155"));

                page.Header().Column(header =>
                {
                    header.Item()
                        .Background("#1D4ED8")
                        .Padding(18)
                        .Column(column =>
                        {
                            column.Item().Text("Career Orientation Test Report")
                                .FontSize(22)
                                .Bold()
                                .FontColor(Colors.White);

                            column.Item().PaddingTop(6).Text($"Generated on: {_result.GeneratedAt:dd MMM yyyy}")
                                .FontSize(10)
                                .FontColor("#DBEAFE");
                        });
                });

                page.Content().PaddingTop(18).Column(column =>
                {
                    column.Spacing(14);

                    ComposeProfile(column);
                    ComposeScores(column);
                    ComposeRecommendedRoles(column);
                    ComposeNextSteps(column);
                });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by Career Guide")
                    .FontSize(9)
                    .FontColor("#64748B");
            });
        }

        private void ComposeProfile(ColumnDescriptor column)
        {
            column.Item().Text("Profile result")
                .FontSize(16)
                .Bold()
                .FontColor("#0F172A");

            column.Item()
                .Background("#EFF6FF")
                .Border(1)
                .BorderColor("#BFDBFE")
                .Padding(14)
                .Column(profile =>
                {
                    profile.Item().Text(_result.ProfileTitle)
                        .FontSize(18)
                        .Bold()
                        .FontColor("#1D4ED8");

                    profile.Item().PaddingTop(8).Text(_result.Summary)
                        .FontSize(10)
                        .LineHeight(1.35f)
                        .FontColor("#334155");
                });
        }

        private void ComposeScores(ColumnDescriptor column)
        {
            column.Item().Text("Career area scores")
                .FontSize(16)
                .Bold()
                .FontColor("#0F172A");

            foreach (var score in _result.AreaScores.OrderByDescending(x => x.Score))
            {
                column.Item()
                    .Border(1)
                    .BorderColor("#E2E8F0")
                    .Padding(10)
                    .Column(item =>
                    {
                        item.Item().Row(row =>
                        {
                            row.RelativeItem().Text(score.Area)
                                .FontSize(12)
                                .Bold()
                                .FontColor("#0F172A");

                            row.ConstantItem(55).AlignRight().Text($"{score.Score}%")
                                .FontSize(12)
                                .Bold()
                                .FontColor("#1D4ED8");
                        });

                        if (!string.IsNullOrWhiteSpace(score.Description))
                        {
                            item.Item().PaddingTop(4).Text(score.Description)
                                .FontSize(9)
                                .FontColor("#64748B");
                        }

                        item.Item().PaddingTop(6)
                            .Background("#E2E8F0")
                            .Height(6)
                            .Width(420)
                            .AlignLeft();

                        item.Item().PaddingTop(-6)
                            .Background("#1D4ED8")
                            .Height(6)
                            .Width(Math.Max(1, score.Score) * 4.2f)
                            .AlignLeft();
                    });
            }
        }

        private void ComposeRecommendedRoles(ColumnDescriptor column)
        {
            if (_result.RecommendedRoles.Count == 0)
                return;

            column.Item().Text("Recommended career directions")
                .FontSize(16)
                .Bold()
                .FontColor("#0F172A");

            column.Item().Column(list =>
            {
                foreach (var role in _result.RecommendedRoles)
                {
                    list.Item().Text($"• {role}")
                        .FontSize(10)
                        .FontColor("#334155");
                }
            });
        }

        private void ComposeNextSteps(ColumnDescriptor column)
        {
            if (_result.NextSteps.Count == 0)
                return;

            column.Item().Text("Suggested next steps")
                .FontSize(16)
                .Bold()
                .FontColor("#0F172A");

            column.Item().Column(list =>
            {
                foreach (var step in _result.NextSteps)
                {
                    list.Item().Text($"• {step}")
                        .FontSize(10)
                        .FontColor("#334155");
                }
            });
        }

        //private void ComposeNotice(ColumnDescriptor column)
        //{
        //    column.Item()
        //        .Background("#FEF3C7")
        //        .Border(1)
        //        .BorderColor("#FDE68A")
        //        .Padding(12)
        //        .Text("Note: This report is generated from your test answers and is not saved automatically in the application.")
        //        .FontSize(9)
        //        .FontColor("#92400E");
        //}
    }
}