using JobCv.Api.Dtos;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace JobCv.Api.Pdf
{
    public class CareerTestPdfDocument : IDocument
    {
        private readonly CareerTestPdfRequestDto _result;

        public CareerTestPdfDocument(CareerTestPdfRequestDto result)
        {
            _result = result;
        }

        private bool IsRomanian => string.Equals(_result.Language, "ro", StringComparison.OrdinalIgnoreCase);

        public DocumentMetadata GetMetadata()
        {
            return DocumentMetadata.Default;
        }

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(36);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(10).FontColor("#334155"));

                page.Content().Column(column =>
                {
                    column.Spacing(14);

                    ComposeReportHeader(column);
                    ComposeProfile(column);
                    ComposeScores(column);
                    ComposeRecommendedRoles(column);
                    ComposeNextSteps(column);
                    ComposeNotice(column);
                });

                page.Footer()
                    .AlignCenter()
                    .Text(IsRomanian ? "Generat de Career Guide" : "Generated by Career Guide")
                    .FontSize(9)
                    .FontColor("#64748B");
            });
        }

        private void ComposeReportHeader(ColumnDescriptor column)
        {
            column.Item()
                .Background("#1D4ED8")
                .Padding(18)
                .Column(header =>
                {
                    header.Item().Text(IsRomanian ? "Raport de interese profesionale" : "Career Interest Profile Report")
                        .FontSize(22)
                        .Bold()
                        .FontColor(Colors.White);

                    header.Item().PaddingTop(6).Text(IsRomanian
                            ? $"Generat la: {_result.GeneratedAt:dd MMM yyyy}"
                            : $"Generated on: {_result.GeneratedAt:dd MMM yyyy}")
                        .FontSize(10)
                        .FontColor("#DBEAFE");
                });
        }

        private void ComposeProfile(ColumnDescriptor column)
        {
            column.Item().Text(IsRomanian ? "Rezultatul profilului" : "Profile result")
                .FontSize(16)
                .Bold()
                .FontColor("#0F172A");

            column.Item()
                .Background("#EFF6FF")
                .Border(1)
                .BorderColor("#BFDBFE")
                .Padding(14)
                .Column(profile =>
                {
                    profile.Item().Text(_result.ProfileTitle)
                        .FontSize(18)
                        .Bold()
                        .FontColor("#1D4ED8");

                    if (!string.IsNullOrWhiteSpace(_result.ProfileCode))
                    {
                        profile.Item().PaddingTop(4).Text(IsRomanian
                                ? $"Cod dominant: {_result.ProfileCode}"
                                : $"Dominant code: {_result.ProfileCode}")
                            .FontSize(10)
                            .Bold()
                            .FontColor("#1E40AF");
                    }

                    profile.Item().PaddingTop(8).Text(_result.Summary)
                        .FontSize(10)
                        .LineHeight(1.35f)
                        .FontColor("#334155");
                });
        }

        private void ComposeScores(ColumnDescriptor column)
        {
            column.Item().Text(IsRomanian ? "Scoruri pe arii de interes" : "Career area scores")
                .FontSize(16)
                .Bold()
                .FontColor("#0F172A");

            foreach (var score in _result.AreaScores.OrderByDescending(x => x.RawScore).ThenByDescending(x => x.Score))
            {
                var rawScore = score.RawScore;
                var maxScore = score.MaxScore > 0 ? score.MaxScore : 10;
                var percent = score.Score;

                if (percent <= 0 && rawScore > 0)
                    percent = (int)Math.Round((double)rawScore / maxScore * 100);

                var progress = Math.Clamp(maxScore == 0 ? percent / 100f : (float)rawScore / maxScore, 0f, 1f);
                var label = string.IsNullOrWhiteSpace(score.AreaCode)
                    ? score.Area
                    : $"{score.AreaCode} - {score.Area}";

                column.Item()
                    .Border(1)
                    .BorderColor("#E2E8F0")
                    .Padding(10)
                    .Column(item =>
                    {
                        item.Item().Row(row =>
                        {
                            row.RelativeItem().Text(label)
                                .FontSize(12)
                                .Bold()
                                .FontColor("#0F172A");

                            row.ConstantItem(90).AlignRight().Text($"{rawScore}/{maxScore} ({percent}%)")
                                .FontSize(12)
                                .Bold()
                                .FontColor("#1D4ED8");
                        });

                        if (!string.IsNullOrWhiteSpace(score.Description))
                        {
                            item.Item().PaddingTop(4).Text(score.Description)
                                .FontSize(9)
                                .FontColor("#64748B");
                        }

                        item.Item().PaddingTop(6)
                            .Background("#E2E8F0")
                            .Height(6)
                            .Width(420)
                            .AlignLeft();

                        item.Item().PaddingTop(-6)
                            .Background("#1D4ED8")
                            .Height(6)
                            .Width(Math.Max(1, progress * 420))
                            .AlignLeft();
                    });
            }
        }

        private void ComposeRecommendedRoles(ColumnDescriptor column)
        {
            if (_result.RecommendedRoles.Count == 0)
                return;

            var careerDirections = GetTaggedRecommendations("DIRECTION");
            var possibleRoles = GetTaggedRecommendations("ROLE");
            var skillsToDevelop = GetTaggedRecommendations("SKILL");
            var legacyItems = _result.RecommendedRoles
                .Where(item => !HasTag(item))
                .Where(item => !string.IsNullOrWhiteSpace(item))
                .ToList();

            column.Item().Text(IsRomanian ? "Recomandări de carieră" : "Career recommendations")
                .FontSize(16)
                .Bold()
                .FontColor("#0F172A");

            if (careerDirections.Count == 0 && possibleRoles.Count == 0 && skillsToDevelop.Count == 0)
            {
                ComposeRecommendationGroup(column,
                    IsRomanian ? "Direcții profesionale recomandate" : "Recommended career directions",
                    legacyItems);
                return;
            }

            ComposeRecommendationGroup(column,
                IsRomanian ? "Direcții de carieră" : "Career directions",
                careerDirections);

            ComposeRecommendationGroup(column,
                IsRomanian ? "Roluri posibile" : "Possible roles",
                possibleRoles);

            ComposeRecommendationGroup(column,
                IsRomanian ? "Competențe de dezvoltat" : "Skills to develop",
                skillsToDevelop);
        }

        private List<string> GetTaggedRecommendations(string tag)
        {
            var prefix = $"{tag}::";

            return _result.RecommendedRoles
                .Where(item => !string.IsNullOrWhiteSpace(item))
                .Where(item => item.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                .Select(item => item.Substring(prefix.Length).Trim())
                .Where(item => !string.IsNullOrWhiteSpace(item))
                .ToList();
        }

        private static bool HasTag(string item)
        {
            if (string.IsNullOrWhiteSpace(item))
                return false;

            return item.StartsWith("DIRECTION::", StringComparison.OrdinalIgnoreCase)
                || item.StartsWith("ROLE::", StringComparison.OrdinalIgnoreCase)
                || item.StartsWith("SKILL::", StringComparison.OrdinalIgnoreCase);
        }

        private static void ComposeRecommendationGroup(ColumnDescriptor column, string title, List<string> items)
        {
            if (items.Count == 0)
                return;

            column.Item().Text(title)
                .FontSize(12)
                .Bold()
                .FontColor("#1E40AF");

            column.Item().Column(list =>
            {
                foreach (var item in items)
                {
                    list.Item().PaddingLeft(8).Text($"• {item}")
                        .FontSize(10)
                        .LineHeight(1.25f)
                        .FontColor("#334155");
                }
            });
        }

        private void ComposeNextSteps(ColumnDescriptor column)
        {
            if (_result.NextSteps.Count == 0)
                return;

            column.Item().Text(IsRomanian ? "Pași recomandați" : "Suggested next steps")
                .FontSize(16)
                .Bold()
                .FontColor("#0F172A");

            column.Item().Column(list =>
            {
                foreach (var step in _result.NextSteps)
                {
                    list.Item().Text($"• {step}")
                        .FontSize(10)
                        .FontColor("#334155");
                }
            });
        }

        private void ComposeNotice(ColumnDescriptor column)
        {
            var note = string.IsNullOrWhiteSpace(_result.SourceAttribution)
                ? DefaultAttribution()
                : _result.SourceAttribution;

            column.Item()
                .Background("#FEF3C7")
                .Border(1)
                .BorderColor("#FDE68A")
                .Padding(12)
                .Column(notice =>
                {
                    notice.Item().Text(IsRomanian ? "Notă" : "Note")
                        .FontSize(11)
                        .Bold()
                        .FontColor("#92400E");

                    notice.Item().PaddingTop(4).Text(note)
                        .FontSize(8)
                        .LineHeight(1.25f)
                        .FontColor("#92400E");

                    notice.Item().PaddingTop(6).Text(IsRomanian
                            ? "Acest raport este orientativ și nu reprezintă un diagnostic psihologic sau o garanție privind alegerea unei cariere."
                            : "This report is for orientation only and is not a psychological diagnosis or a guarantee regarding career choice.")
                        .FontSize(8)
                        .LineHeight(1.25f)
                        .FontColor("#92400E");
                });
        }

        private string DefaultAttribution()
        {
            if (IsRomanian)
            {
                return "Bazat pe O*NET Interest Profiler Short Form Paper-and-Pencil Version, sponsorizat de U.S. Department of Labor, Employment & Training Administration și dezvoltat de National Center for O*NET Development. Adaptarea nu este aprobată, testată sau validată de U.S. Department of Labor / Employment and Training Administration.";
            }

            return "Based on the O*NET Interest Profiler Short Form Paper-and-Pencil Version, sponsored by the U.S. Department of Labor, Employment & Training Administration and developed by the National Center for O*NET Development. This adaptation is not approved, tested, or validated by the U.S. Department of Labor / Employment and Training Administration.";
        }
    }
}
